// Code generated by "stringer -type=FilterTaskState"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PreCrawlFilter-0]
	_ = x[PostCrawlFilter-1]
	_ = x[FinishedFiltering-2]
}

const _FilterTaskState_name = "PreCrawlFilterPostCrawlFilterFinishedFiltering"

var _FilterTaskState_index = [...]uint8{0, 14, 29, 46}

func (i FilterTaskState) String() string {
	if i < 0 || i >= FilterTaskState(len(_FilterTaskState_index)-1) {
		return "FilterTaskState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _FilterTaskState_name[_FilterTaskState_index[i]:_FilterTaskState_index[i+1]]
}
