// Code generated by "stringer -type=IndexerTaskState"; DO NOT EDIT.

package enum

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Indexing-0]
	_ = x[FinishedIndexing-1]
}

const _IndexerTaskState_name = "IndexingFinishedIndexing"

var _IndexerTaskState_index = [...]uint8{0, 8, 24}

func (i IndexerTaskState) String() string {
	if i < 0 || i >= IndexerTaskState(len(_IndexerTaskState_index)-1) {
		return "IndexerTaskState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _IndexerTaskState_name[_IndexerTaskState_index[i]:_IndexerTaskState_index[i+1]]
}
