# .github/workflows/continuous_integration.yml
name: "continuous integration"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.18

    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up golanci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest

    - name: Run Tests
      run: make test

    - name: Build for all OS
      run: make release
